package skir_client

import (
	"bytes"
	"encoding/json"

	"github.com/valyala/fastjson"
)

type Readable struct{}

type KeepUnrecognizedValues struct{}

// Serializer serialises and deserialises values of type T in both JSON and
// binary formats.
type Serializer[T any] struct {
	adapter typeAdapter[T]
}

// newSerializer constructs a Serializer backed by the given adapter.
// For use only by code generated by the skir Go generator.
func newSerializer[T any](a typeAdapter[T]) Serializer[T] {
	return Serializer[T]{adapter: a}
}

func (s Serializer[T]) ToJson(v T, flavor ...Readable) fastjson.Value {
	return s.adapter.toJson(&v, len(flavor) > 0)
}

func (s Serializer[T]) ToJsonCode(v T, flavor ...Readable) string {
	fv := s.adapter.toJson(&v, len(flavor) > 0)
	raw := fv.MarshalTo(nil)
	if len(flavor) == 0 {
		return string(raw)
	}
	var buf bytes.Buffer
	if err := json.Indent(&buf, raw, "", "  "); err != nil {
		panic("skir_client: ToJsonCode: " + err.Error())
	}
	return buf.String()
}

func (s Serializer[T]) FromJson(j fastjson.Value, opts ...KeepUnrecognizedValues) (T, error) {
	return s.adapter.fromJson(j, len(opts) > 0)
}

func (s Serializer[T]) FromJsonCode(code string, opts ...KeepUnrecognizedValues) (T, error) {
	fv, err := fastjson.Parse(code)
	if err != nil {
		var zero T
		return zero, err
	}
	return s.adapter.fromJson(*fv, len(opts) > 0)
}

func (s Serializer[T]) ToBytes(v T) []byte {
	out := binaryOutput{}
	out.out.WriteString("skir")
	s.adapter.encode(&v, &out)
	return out.out.Bytes()
}

func (s Serializer[T]) FromBytes(b []byte, opts ...KeepUnrecognizedValues) (T, error) {
	if len(b) >= 4 && string(b[:4]) == "skir" {
		in := newBinaryInput(b[4:], len(opts) > 0)
		return s.adapter.decode(&in, len(opts) > 0)
	}
	// No "skir" prefix: treat the payload as a UTF-8 JSON string.
	return s.FromJsonCode(string(b), opts...)
}

func (s Serializer[T]) TypeDescriptor() TypeDescriptor {
	return s.adapter.typeDescriptor()
}

// ─────────────────────────────────────────────────────────────────────────────
// typeAdapter – internal interface
// ─────────────────────────────────────────────────────────────────────────────

// typeAdapter is the internal interface implemented by every concrete adapter
// (primitive, array, optional, struct, enum). It is unexported so that only
// adapters defined inside this package can satisfy it.
type typeAdapter[T any] interface {
	isDefault(value *T) bool
	toJson(input *T, readableFlavor bool) fastjson.Value
	fromJson(json fastjson.Value, keepUnrecognizedValues bool) (T, error)
	encode(input *T, out *binaryOutput)
	decode(in *binaryInput, keepUnrecognizedValues bool) (T, error)
	typeDescriptor() TypeDescriptor
}
