package skir_client

import (
	"sort"
	"strings"

	"github.com/valyala/fastjson"
)

// ─────────────────────────────────────────────────────────────────────────────
// internalFieldEntry[T, Builder] – type-erased per-field adapter
// ─────────────────────────────────────────────────────────────────────────────

// internalFieldEntry is the type-erased interface for a single struct field.
// The concrete implementation is typedField[T, Builder, V].
type internalFieldEntry[T, Builder any] interface {
	entryName() string
	entryNumber() int
	entryType() TypeDescriptor
	isEntryDefault(frozen *T) bool
	entryToJson(frozen *T, eolIndent *string, out *strings.Builder)
	setEntryFromJson(mutable Builder, v fastjson.Value, keepUnrecognized bool) error
	encodeEntry(frozen *T, out *binaryOutput)
	decodeEntry(mutable Builder, in *binaryInput, keepUnrecognized bool)
}

type typedField[T, Builder, V any] struct {
	name    string
	number  int
	adapter typeAdapter[V]
	getter  func(*T) V
	setter  func(Builder, V)
}

func (f *typedField[T, Builder, V]) entryName() string         { return f.name }
func (f *typedField[T, Builder, V]) entryNumber() int          { return f.number }
func (f *typedField[T, Builder, V]) entryType() TypeDescriptor { return f.adapter.typeDescriptor() }

func (f *typedField[T, Builder, V]) isEntryDefault(frozen *T) bool {
	v := f.getter(frozen)
	return f.adapter.isDefault(&v)
}

func (f *typedField[T, Builder, V]) entryToJson(frozen *T, eolIndent *string, out *strings.Builder) {
	v := f.getter(frozen)
	f.adapter.toJson(&v, eolIndent, out)
}

func (f *typedField[T, Builder, V]) setEntryFromJson(mutable Builder, fv fastjson.Value, keepUnrecognized bool) error {
	v, err := f.adapter.fromJson(fv, keepUnrecognized)
	if err != nil {
		return err
	}
	f.setter(mutable, v)
	return nil
}

func (f *typedField[T, Builder, V]) encodeEntry(frozen *T, out *binaryOutput) {
	v := f.getter(frozen)
	f.adapter.encode(&v, out)
}

func (f *typedField[T, Builder, V]) decodeEntry(mutable Builder, in *binaryInput, keepUnrecognized bool) {
	v, _ := f.adapter.decode(in, keepUnrecognized)
	f.setter(mutable, v)
}

// ─────────────────────────────────────────────────────────────────────────────
// Internal__StructAdapter[T, Builder]
// ─────────────────────────────────────────────────────────────────────────────

// Internal__StructAdapter implements typeAdapter[T] for a skir struct type.
// For use only by code generated by the skir Go generator.
//
//   - T is the frozen (immutable) struct type.
//   - Builder is the partial-builder type (e.g. *Foo_partialBuilderType).
//
// Usage: call NewStructAdapter, then AddField / AddRemovedNumber for each
// field, then Finalize before using the adapter.
type Internal__StructAdapter[T any, Builder any] struct {
	defaultInstance       T
	newMutable            func() Builder
	toFrozen              func(Builder) T
	modulePath            string
	qualifiedName         string
	docString             string
	getUnrecognizedFields func(*T) *Internal__UnrecognizedFields
	setUnrecognizedFields func(Builder, *Internal__UnrecognizedFields)

	orderedEntries []internalFieldEntry[T, Builder] // sorted by number after Finalize
	nameToEntry    map[string]internalFieldEntry[T, Builder]
	slotToEntry    []internalFieldEntry[T, Builder] // indexed by slot; nil = removed/absent
	removedNumbers map[int]struct{}
	maxNumber      int

	desc      *StructDescriptor // set by Finalize
	finalized bool
}

// NewStructAdapter creates a new Internal__StructAdapter.
// Call AddField / AddRemovedNumber for each field and removed number,
// then Finalize before using the adapter.
func Internal__NewStructAdapter[T, Builder any](
	defaultInstance T,
	newMutable func() Builder,
	toFrozen func(Builder) T,
	modulePath, qualifiedName, doc string,
	getUnrecognizedFields func(*T) *Internal__UnrecognizedFields,
	setUnrecognizedFields func(Builder, *Internal__UnrecognizedFields),
) *Internal__StructAdapter[T, Builder] {
	return &Internal__StructAdapter[T, Builder]{
		defaultInstance:       defaultInstance,
		newMutable:            newMutable,
		toFrozen:              toFrozen,
		modulePath:            modulePath,
		qualifiedName:         qualifiedName,
		docString:             doc,
		getUnrecognizedFields: getUnrecognizedFields,
		setUnrecognizedFields: setUnrecognizedFields,
		nameToEntry:           make(map[string]internalFieldEntry[T, Builder]),
		removedNumbers:        make(map[int]struct{}),
		maxNumber:             -1,
	}
}

// AddField registers a struct field on an in-progress Internal__StructAdapter.
// Must be called before Finalize.
//
// This is a package-level function (not a method) because Go does not permit
// additional type parameters on methods.
func AddField[T, Builder, V any](
	a *Internal__StructAdapter[T, Builder],
	name string,
	number int,
	ser Serializer[V],
	getter func(*T) V,
	setter func(Builder, V),
) {
	if a.finalized {
		panic("skir_client: AddField called after Finalize")
	}
	f := &typedField[T, Builder, V]{
		name:    name,
		number:  number,
		adapter: ser.adapter,
		getter:  getter,
		setter:  setter,
	}
	a.orderedEntries = append(a.orderedEntries, f)
	a.nameToEntry[name] = f
	if number > a.maxNumber {
		a.maxNumber = number
	}
}

// AddRemovedNumber registers a field number that was removed from the schema.
// Must be called before Finalize.
func (a *Internal__StructAdapter[T, Builder]) AddRemovedNumber(number int) {
	if a.finalized {
		panic("skir_client: AddRemovedNumber called after Finalize")
	}
	a.removedNumbers[number] = struct{}{}
	if number > a.maxNumber {
		a.maxNumber = number
	}
}

// Finalize prepares the adapter for serialization.
// Must be called once, after all AddField and AddRemovedNumber calls.
func (a *Internal__StructAdapter[T, Builder]) Finalize() {
	if a.finalized {
		panic("skir_client: Finalize called more than once")
	}
	a.finalized = true

	sort.Slice(a.orderedEntries, func(i, j int) bool {
		return a.orderedEntries[i].entryNumber() < a.orderedEntries[j].entryNumber()
	})

	slotCount := 0
	if a.maxNumber >= 0 {
		slotCount = a.maxNumber + 1
	}
	a.slotToEntry = make([]internalFieldEntry[T, Builder], slotCount)
	for _, e := range a.orderedEntries {
		a.slotToEntry[e.entryNumber()] = e
	}

	fields := make([]*StructField, len(a.orderedEntries))
	for i, e := range a.orderedEntries {
		fields[i] = &StructField{
			Name:   e.entryName(),
			Number: e.entryNumber(),
			Type:   e.entryType(),
		}
	}
	a.desc = newStructDescriptor(
		a.modulePath,
		a.qualifiedName,
		a.docString,
		a.removedNumbers,
		fields,
	)
}

// ─────────────────────────────────────────────────────────────────────────────
// typeAdapter[T] implementation
// ─────────────────────────────────────────────────────────────────────────────

func (a *Internal__StructAdapter[T, Builder]) isDefault(value *T) bool {
	if a.getUnrecognizedFields(value) != nil {
		return false
	}
	for _, e := range a.orderedEntries {
		if !e.isEntryDefault(value) {
			return false
		}
	}
	return true
}

func (a *Internal__StructAdapter[T, Builder]) toJson(input *T, eolIndent *string, out *strings.Builder) {
	if eolIndent != nil {
		a.toReadableJson(input, eolIndent, out)
	} else {
		a.toDenseJson(input, out)
	}
}

// toDenseJson writes input as a JSON array.
// Trailing default slots are omitted (array length = last non-default slot + 1),
// unless the struct carries unrecognized fields from a newer schema version, in
// which case all recognised slots are written followed by the stored unrecognized
// JSON elements.
func (a *Internal__StructAdapter[T, Builder]) toDenseJson(input *T, out *strings.Builder) {
	unrecognized := a.getUnrecognizedFields(input)
	out.WriteByte('[')
	if unrecognized != nil && unrecognized.jsonElements != nil {
		// Write all recognised slots, then append the stored unrecognized elements.
		recognizedCount := len(a.slotToEntry)
		for i := 0; i < recognizedCount; i++ {
			if i > 0 {
				out.WriteByte(',')
			}
			if a.slotToEntry[i] != nil {
				a.slotToEntry[i].entryToJson(input, nil, out)
			} else {
				out.WriteByte('0')
			}
		}
		for i, elem := range unrecognized.jsonElements {
			if recognizedCount+i > 0 {
				out.WriteByte(',')
			}
			out.Write(elem.MarshalTo(nil))
		}
	} else {
		// No unrecognized fields: omit trailing default slots.
		slotCount := a.getSlotCount(input)
		for i := 0; i < slotCount; i++ {
			if i > 0 {
				out.WriteByte(',')
			}
			if i < len(a.slotToEntry) && a.slotToEntry[i] != nil {
				a.slotToEntry[i].entryToJson(input, nil, out)
			} else {
				out.WriteByte('0')
			}
		}
	}
	out.WriteByte(']')
}

// toReadableJson writes input as a JSON object, omitting default fields.
func (a *Internal__StructAdapter[T, Builder]) toReadableJson(input *T, eolIndent *string, out *strings.Builder) {
	out.WriteByte('{')
	childIndent := *eolIndent + "  "
	first := true
	for _, e := range a.orderedEntries {
		if e.isEntryDefault(input) {
			continue
		}
		if !first {
			out.WriteByte(',')
		}
		first = false
		out.WriteString(childIndent)
		writeJsonEscapedString(e.entryName(), out)
		out.WriteString(": ")
		e.entryToJson(input, &childIndent, out)
	}
	if !first {
		out.WriteString(*eolIndent)
	}
	out.WriteByte('}')
}

// getSlotCount returns the number of slots needed to encode input:
// the field number of the last non-default field + 1, or 0 if all are default.
func (a *Internal__StructAdapter[T, Builder]) getSlotCount(input *T) int {
	for i := len(a.orderedEntries) - 1; i >= 0; i-- {
		if !a.orderedEntries[i].isEntryDefault(input) {
			return a.orderedEntries[i].entryNumber() + 1
		}
	}
	return 0
}

func (a *Internal__StructAdapter[T, Builder]) fromJson(v fastjson.Value, keepUnrecognized bool) (T, error) {
	switch v.Type() {
	case fastjson.TypeNumber:
		// Dense default: 0 → return default instance.
		return a.defaultInstance, nil
	case fastjson.TypeArray:
		return a.fromDenseJson(v, keepUnrecognized)
	case fastjson.TypeObject:
		return a.fromReadableJson(v)
	default:
		return a.defaultInstance, nil
	}
}

func (a *Internal__StructAdapter[T, Builder]) fromDenseJson(arr fastjson.Value, keepUnrecognized bool) (T, error) {
	items, err := arr.Array()
	if err != nil {
		return a.defaultInstance, err
	}
	mutable := a.newMutable()
	recognizedCount := len(a.slotToEntry)
	numSlotsToFill := len(items)
	if numSlotsToFill > recognizedCount {
		// The encoded array has slots from a newer schema version.
		if keepUnrecognized {
			extraItems := items[recognizedCount:]
			jsonElements := make([]*fastjson.Value, len(extraItems))
			copy(jsonElements, extraItems)
			a.setUnrecognizedFields(mutable, Internal__NewUnrecognizedFieldsFromJson(len(items), jsonElements))
		}
		numSlotsToFill = recognizedCount
	}
	for _, e := range a.orderedEntries {
		n := e.entryNumber()
		if n >= numSlotsToFill {
			break
		}
		if err := e.setEntryFromJson(mutable, *items[n], keepUnrecognized); err != nil {
			return a.defaultInstance, err
		}
	}
	return a.toFrozen(mutable), nil
}

func (a *Internal__StructAdapter[T, Builder]) fromReadableJson(obj fastjson.Value) (T, error) {
	mutable := a.newMutable()
	jsonObj, err := obj.Object()
	if err != nil {
		return a.defaultInstance, err
	}
	var visitErr error
	jsonObj.Visit(func(key []byte, v *fastjson.Value) {
		if visitErr != nil {
			return
		}
		if e := a.nameToEntry[string(key)]; e != nil {
			visitErr = e.setEntryFromJson(mutable, *v, false)
		}
	})
	if visitErr != nil {
		return a.defaultInstance, visitErr
	}
	return a.toFrozen(mutable), nil
}

func (a *Internal__StructAdapter[T, Builder]) encode(input *T, out *binaryOutput) {
	unrecognized := a.getUnrecognizedFields(input)
	var totalSlotCount int
	var recognizedSlotCount int
	var unrecognizedBytes []byte
	if unrecognized != nil && unrecognized.bytes != nil {
		// Round-trip binary unrecognized fields verbatim.
		totalSlotCount = unrecognized.totalSlotCount
		recognizedSlotCount = len(a.slotToEntry)
		unrecognizedBytes = unrecognized.bytes
	} else {
		// No binary unrecognized fields: omit trailing default slots.
		totalSlotCount = a.getSlotCount(input)
		recognizedSlotCount = totalSlotCount
	}
	if totalSlotCount <= 3 {
		out.writeUint8(uint8(246 + totalSlotCount))
	} else {
		out.writeUint8(250)
		encodeUint32(uint32(totalSlotCount), out)
	}
	for i := 0; i < recognizedSlotCount; i++ {
		if i < len(a.slotToEntry) && a.slotToEntry[i] != nil {
			a.slotToEntry[i].encodeEntry(input, out)
		} else {
			out.writeUint8(0) // removed or absent field
		}
	}
	if unrecognizedBytes != nil {
		out.out.Write(unrecognizedBytes)
	}
}

func (a *Internal__StructAdapter[T, Builder]) decode(in *binaryInput, keepUnrecognized bool) (T, error) {
	wire := in.readUint8()
	if wire == 0 || wire == 246 {
		return a.defaultInstance, nil
	}
	mutable := a.newMutable()
	var encodedSlotCount int
	if wire == 250 {
		encodedSlotCount = int(decodeNumber(in))
	} else {
		encodedSlotCount = int(wire) - 246
	}
	recognizedCount := len(a.slotToEntry)
	slotsToFill := encodedSlotCount
	if slotsToFill > recognizedCount {
		slotsToFill = recognizedCount
	}
	for i := 0; i < slotsToFill; i++ {
		if a.slotToEntry[i] != nil {
			a.slotToEntry[i].decodeEntry(mutable, in, keepUnrecognized)
		} else {
			skipValue(in) // removed field
		}
	}
	if encodedSlotCount > recognizedCount {
		if keepUnrecognized {
			// Capture the raw bytes of the unrecognized slots so they can be
			// round-tripped back to binary encoding later.
			start := in.offset
			for i := recognizedCount; i < encodedSlotCount; i++ {
				skipValue(in)
			}
			unrecognizedBytes := make([]byte, in.offset-start)
			copy(unrecognizedBytes, in.data[start:in.offset])
			a.setUnrecognizedFields(mutable, Internal__NewUnrecognizedFieldsFromBytes(encodedSlotCount, unrecognizedBytes))
		} else {
			for i := recognizedCount; i < encodedSlotCount; i++ {
				skipValue(in)
			}
		}
	}
	return a.toFrozen(mutable), nil
}

func (a *Internal__StructAdapter[T, Builder]) typeDescriptor() TypeDescriptor {
	return a.desc
}

// Serializer returns a Serializer[T] backed by this adapter.
func (a *Internal__StructAdapter[T, Builder]) Serializer() Serializer[T] {
	return newSerializer(a)
}

// ─────────────────────────────────────────────────────────────────────────────
// skipValue – advance past one encoded value without decoding it
// ─────────────────────────────────────────────────────────────────────────────

// skipValue advances in past one complete encoded value without decoding it.
// Used for removed fields and for unrecognized fields from a newer schema.
func skipValue(in *binaryInput) {
	wire := in.readUint8()
	switch {
	case wire < 232:
		// Single-byte value; already consumed.
	case wire == 232:
		in.readUint16()
	case wire == 233:
		in.readUint32()
	case wire == 234:
		in.readHash64()
	case wire == 235:
		in.readUint8()
	case wire == 236:
		in.readUint16()
	case wire == 237:
		in.readInt32()
	case wire == 238, wire == 239:
		in.readInt64()
	case wire == 240:
		in.readFloat32()
	case wire == 241:
		in.readFloat64()
	case wire == 242, wire == 244:
		// Empty string or bytes: nothing further to read.
	case wire == 243, wire == 245:
		// String or bytes with a length prefix followed by N bytes.
		n := decodeNumber(in)
		in.readBytes(int(n))
	case wire == 246:
		// Empty array or struct: nothing further to read.
	case wire == 247, wire == 248, wire == 249:
		n := int(wire) - 246
		for i := 0; i < n; i++ {
			skipValue(in)
		}
	case wire == 250:
		n := int(decodeNumber(in))
		for i := 0; i < n; i++ {
			skipValue(in)
		}
	case wire == 255:
		// Optional absent: nothing further to read.
	}
}
