// Actually output JSON to string...
// Look at the Arena thing...
// Add comments on getters returning a MaybeStar about whether the pointer can be nil or not
// RPC code
// Reflection
// set up CI
// Use real `const`s for constants... No pointer type for consts if not complex type...

import {
  type CodeGenerator,
  type Constant,
  type Doc,
  type Field,
  type Method,
  type Module,
  type RecordKey,
  type RecordLocation,
  type ResolvedType,
  convertCase,
} from "skir-internal";
import { z } from "zod";
import {
  getClassName,
  modulePathToAlias,
  modulePathToPackageName,
  modulePathToPackagePath,
  structFieldToGetterName,
} from "./naming.js";
import { TypeSpeller } from "./type_speller.js";

const Config = z.strictObject({
  goModuleName: z
    .string()
    .regex(/^[a-zA-Z0-9][a-zA-Z0-9._~-]*(\/[a-zA-Z0-9][a-zA-Z0-9._~-]*)*$/),
});

type Config = z.infer<typeof Config>;

class GoCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-go-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const { recordMap, config } = input;
    const outputFiles: CodeGenerator.OutputFile[] = [];
    for (const module of input.modules) {
      const packagePath = modulePathToPackagePath(module.path);
      const packageName = modulePathToPackageName(module.path);
      outputFiles.push({
        path: packagePath.concat(`/${packageName}.go`),
        code: new GoSourceFileGenerator(module, recordMap, config).generate(),
      });
    }
    return { files: outputFiles };
  }
}

// Generates the code for one Go file.
class GoSourceFileGenerator {
  constructor(
    private readonly inModule: Module,
    recordMap: ReadonlyMap<RecordKey, RecordLocation>,
    private readonly config: Config,
  ) {
    this.typeSpeller = new TypeSpeller(recordMap, inModule.path);
  }

  generate(): string {
    const packageName = modulePathToPackageName(this.inModule.path);

    // http://patorjk.com/software/taag/#f=Doom&t=Do%20not%20edit
    this.push(
      `//  ______                        _               _  _  _
      //  |  _  \\                      | |             | |(_)| |
      //  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
      //  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _\` || || __|
      //  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_ 
      //  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|
      //
      // Generated by skir-go-gen
      // Home: https://github.com/gepheum/skir-go-gen
      //
      // To install the Skir client library, run:
      //   go get github.com/gepheum/skir-go-client

      package `,
      packageName,
      "_skir\n\n",
    );

    this.writeImports();

    for (const record of this.inModule.records) {
      const { recordType } = record.record;
      if (recordType === "struct") {
        this.writeTypesForStruct(record);
      } else {
        this.writeTypesForEnum(record);
      }
    }

    if (this.inModule.methods.length) {
      this.pushSeparator("Methods");
      for (const method of this.inModule.methods) {
        this.writeMethod(method);
      }
    }

    if (this.inModule.constants.length) {
      this.pushSeparator("Constants");
      for (const constant of this.inModule.constants) {
        this.writeConstant(constant);
      }
    }

    // To disable unused import errors.
    this.push(
      "var _ = skir_client.Array[bool]{}\n",
      "var _ = atomic.Pointer[bool]{}\n",
      "var _ = time.Time{}\n",
    );

    return this.joinLinesAndFixFormatting();
  }

  private writeImports(): void {
    // TODO: rm e2e-test
    this.push(`import (
      "e2e-test/skir_client"
      "sync/atomic"
      "time"
    `);
    for (const importedPath of Object.keys(this.inModule.pathToImportedNames)) {
      const alias = modulePathToAlias(importedPath);
      const packagePath = modulePathToPackagePath(importedPath);
      this.push(
        `${alias} "${this.config.goModuleName}/skirout/${packagePath}"\n`,
      );
    }
    this.push(")\n\n");
  }

  private writeTypesForStruct(struct: RecordLocation): void {
    this.pushSeparator(
      "struct ".concat(
        struct.recordAncestors.map((r) => r.name.text).join("."),
      ),
    );
    const { typeSpeller } = this;
    const fields = [...struct.record.fields].sort((a, b) =>
      a.name.text.localeCompare(b.name.text),
    );
    const className = getClassName(struct);

    // Define the frozen struct.
    this.push(
      commentify([docToCommentText(struct.record.doc), "\nDeeply immutable."]),
    );
    this.push(`type ${className} struct {\n`);
    for (const field of fields) {
      const fieldName = "_" + convertCase(field.name.text, "lowerCamel");
      const fieldType = field.type!;
      const goType = typeSpeller.getGoType(fieldType);
      const maybeStar = field.isRecursive === "hard" ? "*" : "";
      this.push(`${fieldName} ${maybeStar}${goType}\n`);
      const keyedArrayHelper = this.getKeyedArrayHelper(fieldType);
      if (keyedArrayHelper) {
        const { mapType } = keyedArrayHelper;
        this.push(`${fieldName}_indexed *atomic.Pointer[${mapType}]\n`);
      }
    }
    this.push(`__unrecognized *skir_client.Internal__UnrecognizedFields\n`);
    this.push("}\n\n");

    // Write the getters.
    for (const field of fields) {
      const fieldName = structFieldToGetterName(field);
      const goType = typeSpeller.getGoType(field.type!);
      const type = field.type!;
      const isStructType = this.isStructType(type);
      const fieldAccess = "s._" + convertCase(field.name.text, "lowerCamel");
      const returnType = isStructType ? `*${goType}` : goType;
      this.push(commentify(docToCommentText(field.doc)));
      this.push(`func (s *${className}) ${fieldName}() ${returnType} {\n`);
      if (field.isRecursive === "hard") {
        // Stored as *GoType; return directly.
        if (type.kind !== "record") {
          throw new TypeError();
        }
        const otherRecord = typeSpeller.recordMap.get(type.key)!;
        const otherClassName = getClassName(otherRecord);
        this.push(`maybeRet := ${fieldAccess}\n`);
        this.push("if maybeRet != nil {\n");
        this.push("  return maybeRet\n");
        this.push("} else {\n");
        this.push(`  return &_${otherClassName}_default\n`);
        this.push("}\n");
      } else if (isStructType) {
        // Stored as GoType value; return a pointer to it.
        this.push(`return &${fieldAccess}\n`);
      } else {
        this.push(`return ${fieldAccess}\n`);
      }
      this.push("}\n\n");
    }

    // Write the Search methods for keyed array fields.
    for (const field of fields) {
      const keyedArrayHelper = this.getKeyedArrayHelper(field.type!);
      if (!keyedArrayHelper) {
        continue;
      }
      const {
        mapType,
        itemType,
        exposedKeyType,
        itemToComparableExpr,
        exposedKeyToComparableExpr,
      } = keyedArrayHelper;
      const fieldName = convertCase(field.name.text, "UpperCamel");
      const rawFieldAccess = "s._" + convertCase(field.name.text, "lowerCamel");
      const indexingAccess = `${rawFieldAccess}_indexed`;
      this.push(
        `func (s *${className}) Search${fieldName}(k ${exposedKeyType}) *${itemType} {\n`,
      );
      this.push(`indexingPtr := ${indexingAccess}\n`);
      this.push("m := indexingPtr.Load()\n");
      this.push("if m == nil {\n");
      this.push(`newMap := make(${mapType}, ${rawFieldAccess}.Len())\n`);
      this.push(`for _, e := range ${rawFieldAccess}.All() {\n`);
      this.push(`newMap[${itemToComparableExpr}] = e\n`);
      this.push("}\n");
      this.push("indexingPtr.Store(&newMap)\n");
      this.push("m = &newMap\n");
      this.push("}\n");
      this.push(`return (*m)[${exposedKeyToComparableExpr}]\n`);
      this.push("}\n\n");
    }

    // Write the String() method
    this.push(`func (s *${className}) String() string {\n`);
    this.push(
      `return ${className}_serializer().ToJson(*s, skir_client.Readable{})\n`,
    );
    this.push("}\n\n");

    // Write ToBuilder() method.
    this.push(
      `func (s ${className}) ToBuilder() *${className}_partialBuilderType {\n`,
    );
    this.push(`  return &${className}_partialBuilderType{s: s}\n`);
    this.push("}\n\n");

    // Define the builder interfaces.
    const fieldToBuilderName = (f: Field | undefined): string =>
      f
        ? className + "_builderAt" + convertCase(f.name.text, "UpperCamel")
        : className + "_builderDone";
    for (const [i, field] of fields.entries()) {
      const fieldName = convertCase(field.name.text, "UpperCamel");
      const fieldType = typeSpeller.getGoType(field.type!);
      const nextField = fields[i + 1];
      this.push(`type ${fieldToBuilderName(field)} interface {\n`);
      const returnType = fieldToBuilderName(nextField);
      this.push(`Set${fieldName}(v ${fieldType}) ${returnType}\n`);
      if (field.type!.kind === "array") {
        const itemType = typeSpeller.getGoType(field.type!.item);
        this.push(`Set${fieldName}_fromSlice(v []${itemType}) ${returnType}\n`);
      }
      this.push("}\n\n");
    }
    this.push(`type ${className}_builderDone interface {\n`);
    this.push(`  Build() ${className}\n`);
    this.push("}\n\n");

    // Define the builder struct.
    this.push(`type _${className}_builder struct {\n`);
    this.push(`s ${className}\n`);
    this.push("}\n\n");

    // Write the setters of the builder.
    for (const [i, field] of fields.entries()) {
      const builderName = `_${className}_builder`;
      const fieldName = convertCase(field.name.text, "UpperCamel");
      const fieldType = typeSpeller.getGoType(field.type!);
      const nextField = fields[i + 1];
      const returnType = fieldToBuilderName(nextField);
      this.push(
        `func (b *${builderName}) Set${fieldName}(v ${fieldType}) ${returnType} {\n`,
      );
      const fieldAccess = "b.s._" + convertCase(field.name.text, "lowerCamel");
      if (field.isRecursive === "hard") {
        this.push(`  ${fieldAccess} = &v\n`);
      } else {
        this.push(`  ${fieldAccess} = v\n`);
      }
      const setterKeyedArrayHelper = this.getKeyedArrayHelper(field.type!);
      if (setterKeyedArrayHelper) {
        this.push(
          `  ${fieldAccess}_indexed = &atomic.Pointer[${setterKeyedArrayHelper.mapType}]{}\n`,
        );
      }
      this.push("  return b\n");
      this.push("}\n\n");
      if (field.type!.kind === "array") {
        const itemType = typeSpeller.getGoType(field.type!.item);
        this.push(
          `func (b *${builderName}) Set${fieldName}_fromSlice(v []${itemType}) ${returnType} {\n`,
        );
        this.push(
          `  return b.Set${fieldName}(skir_client.ArrayFromSlice(v))\n`,
        );
        this.push("}\n\n");
      }
    }

    // Write the Build() method of the builder.
    this.push(`func (b *_${className}_builder) Build() ${className} {\n`);
    this.push("  return b.s\n");
    this.push("}\n\n");

    // Write the builder factory function.
    this.push(
      `func ${className}_builder() ${fieldToBuilderName(fields[0])} {\n`,
    );
    this.push(`  return &_${className}_builder{}\n`);
    this.push("}\n\n");

    // Define the partial builder type.
    this.push(`type ${className}_partialBuilderType struct {\n`);
    this.push(`s ${className}\n`);
    this.push("}\n\n");

    // Write the setters for the partial builder.
    for (const field of fields) {
      const builderTypeName = `${className}_partialBuilderType`;
      const fieldName = convertCase(field.name.text, "UpperCamel");
      const fieldType = typeSpeller.getGoType(field.type!);
      this.push(
        `func (b *${builderTypeName}) Set${fieldName}(v ${fieldType}) *${builderTypeName} {\n`,
      );
      const fieldAccess = "b.s._" + convertCase(field.name.text, "lowerCamel");
      if (field.isRecursive === "hard") {
        this.push(`  ${fieldAccess} = &v\n`);
      } else {
        this.push(`  ${fieldAccess} = v\n`);
      }
      const partialSetterKeyedArrayHelper = this.getKeyedArrayHelper(
        field.type!,
      );
      if (partialSetterKeyedArrayHelper) {
        this.push(
          `  ${fieldAccess}_indexed = &atomic.Pointer[${partialSetterKeyedArrayHelper.mapType}]{}\n`,
        );
      }
      this.push("  return b\n");
      this.push("}\n\n");
      if (field.type!.kind === "array") {
        const itemType = typeSpeller.getGoType(field.type!.item);
        this.push(
          `func (b *${builderTypeName}) Set${fieldName}_fromSlice(v []${itemType}) *${builderTypeName} {\n`,
        );
        this.push(
          `  return b.Set${fieldName}(skir_client.ArrayFromSlice(v))\n`,
        );
        this.push("}\n\n");
      }
    }

    // Write Build() for the partial builder.
    this.push(
      `func (b *${className}_partialBuilderType) Build() ${className} {\n`,
    );
    this.push("  return b.s\n");
    this.push("}\n\n");

    // Write the partial builder factory function.
    this.push(
      `func ${className}_partialBuilder() *${className}_partialBuilderType {\n`,
    );
    this.push(
      `  return &${className}_partialBuilderType{s: _${className}_default}\n`,
    );
    this.push("}\n\n");

    // Default struct value.
    this.push(`var _${className}_default = ${className}{\n`);
    for (const field of fields) {
      const fieldType = field.type!;
      const keyedArrayHelper = this.getKeyedArrayHelper(fieldType);
      if (keyedArrayHelper) {
        const { mapType } = keyedArrayHelper;
        const fieldName = "_"
          .concat(convertCase(field.name.text, "lowerCamel"))
          .concat("_indexed");
        this.push(`  ${fieldName}: &atomic.Pointer[${mapType}]{},\n`);
      }
    }
    this.push("}\n\n");
    this.push(`func ${className}_default() *${className} {\n`);
    this.push(`  return &_${className}_default\n`);
    this.push("}\n\n");

    // Adapter
    const qualifiedRecordName = struct.recordAncestors
      .map((r) => r.name.text)
      .join(".");
    this.push(
      `var _${className}_adapter = skir_client.Internal__NewStructAdapter(\n`,
    );
    this.push(`_${className}_default,\n`);
    this.push(`${className}_partialBuilder,\n`);
    this.push(
      `func(b *${className}_partialBuilderType) ${className} { return b.Build() },\n`,
    );
    this.push(`${toGoStringLiteral(struct.modulePath)},\n`);
    this.push(`${toGoStringLiteral(qualifiedRecordName)},\n`);
    this.push(`${toGoStringLiteral(docToCommentText(struct.record.doc))},\n`);
    this.push(
      `func(s *${className}) *skir_client.Internal__UnrecognizedFields { return s.__unrecognized },\n`,
    );
    this.push(
      `func(b *${className}_partialBuilderType, u *skir_client.Internal__UnrecognizedFields) { b.s.__unrecognized = u },\n`,
    );
    this.push(")\n\n");

    // Serializer function.
    this.push(
      `func ${className}_serializer() skir_client.Serializer[${className}] {\n`,
    );
    this.push(`return _${className}_adapter.Serializer()\n`);
    this.push("}\n\n");

    // init() – add fields, removed numbers, finalize.
    this.push("func init() {\n");
    for (const field of struct.record.fields) {
      const fieldName = "_" + convertCase(field.name.text, "lowerCamel");
      const goType = typeSpeller.getGoType(field.type!);
      const isHardRecursive = field.isRecursive === "hard";
      // For hard-recursive fields the struct stores a pointer; wrap with Optional.
      const serializerExpr = isHardRecursive
        ? `skir_client.OptionalSerializer(\n${typeSpeller.getSerializerExpression(field.type!)},\n)`
        : typeSpeller.getSerializerExpression(field.type!);
      const storedGoType = isHardRecursive ? `*${goType}` : goType;
      this.push(
        `skir_client.AddField(\n` +
          `_${className}_adapter,\n` +
          `${toGoStringLiteral(field.name.text)},\n` +
          `${field.number},\n` +
          `${serializerExpr},\n` +
          `func(s *${className}) ${storedGoType} { return s.${fieldName} },\n` +
          `func(b *${className}_partialBuilderType, v ${storedGoType}) { b.s.${fieldName} = v },\n` +
          ")\n",
      );
    }
    for (const removedNumber of struct.record.removedNumbers) {
      this.push(`_${className}_adapter.AddRemovedNumber(${removedNumber})\n`);
    }
    this.push(`_${className}_adapter.Finalize()\n`);
    this.push("}\n\n");
  }

  private writeTypesForEnum(record: RecordLocation): void {
    this.pushSeparator(
      "enum ".concat(record.recordAncestors.map((r) => r.name.text).join(".")),
    );
    const { typeSpeller } = this;
    const variants = [...record.record.fields].sort((a, b) =>
      a.name.text.localeCompare(b.name.text),
    );
    const className = getClassName(record);
    const constantVariants = variants.filter((v) => !v.type);
    const wrapperVariants = variants.filter((v) => v.type);
    const kindType = `${className}_kind`;

    // Define the Kind type and its constants.
    this.push(
      `// ${kindType} identifies which variant a ${className} holds.\n`,
    );
    this.push(`type ${kindType} int\n\n`);
    this.push(`const (\n`);
    this.push(`${kindType}_Unknown ${kindType} = iota\n`);
    for (const variant of constantVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      this.push(`${kindType}_${name}Const\n`);
    }
    for (const variant of wrapperVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      this.push(`${kindType}_${name}Wrapper\n`);
    }
    this.push(")\n\n");

    // Define the frozen enum struct.
    this.push(
      commentify([docToCommentText(record.record.doc), "\nDeeply immutable."]),
    );
    this.push(`type ${className} struct {\n`);
    this.push(`kind ${kindType}\n`);
    this.push("value any\n");
    this.push("}\n\n");

    // Kind() getter.
    this.push(`func (e ${className}) Kind() ${kindType} {\n`);
    this.push("return e.kind\n");
    this.push("}\n\n");

    // IsUnknown() method.
    this.push(`func (e ${className}) IsUnknown() bool {\n`);
    this.push(`return e.kind == ${kindType}_Unknown\n`);
    this.push("}\n\n");

    // Is...() methods for constant variants.
    for (const variant of constantVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      this.push(`func (e ${className}) Is${name}Const() bool {\n`);
      this.push(`return e.kind == ${kindType}_${name}Const\n`);
      this.push("}\n\n");
    }

    // Is...() methods for wrapper variants.
    for (const variant of wrapperVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      this.push(`func (e ${className}) Is${name}Wrapper() bool {\n`);
      this.push(`return e.kind == ${kindType}_${name}Wrapper\n`);
      this.push("}\n\n");
    }

    // Factory functions for constant variants.
    this.push(
      `// ${className}_Unknown is the default value for fields of type ${className}.\n`,
    );
    this.push(`func ${className}_Unknown() ${className} {\n`);
    this.push(`return ${className}{}\n`);
    this.push("}\n\n");
    for (const variant of constantVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      this.push(commentify(docToCommentText(variant.doc)));
      this.push(`func ${className}_${name}Const() ${className} {\n`);
      this.push(`return ${className}{kind: ${kindType}_${name}Const}\n`);
      this.push("}\n\n");
    }

    // Factory functions for wrapper variants.
    for (const variant of wrapperVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      const goType = typeSpeller.getGoType(variant.type!);
      this.push(commentify(docToCommentText(variant.doc)));
      this.push(
        `func ${className}_${name}Wrapper(v ${goType}) ${className} {\n`,
      );
      this.push(
        `return ${className}{kind: ${kindType}_${name}Wrapper, value: v}\n`,
      );
      this.push("}\n\n");
    }

    // Unwrap...() methods for wrapper variants.
    for (const variant of wrapperVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      const goType = typeSpeller.getGoType(variant.type!);
      const isStructType = this.isStructType(variant.type!);
      const returnType = isStructType ? `*${goType}` : goType;
      this.push(`func (e ${className}) Unwrap${name}() ${returnType} {\n`);
      this.push(`if e.kind != ${kindType}_${name}Wrapper {\n`);
      this.push(
        `panic("${className}.Unwrap${name}(): kind is not ${name}Wrapper")\n`,
      );
      this.push("}\n");
      if (isStructType) {
        this.push(`v := e.value.(${goType})\n`);
        this.push("return &v\n");
      } else {
        this.push(`return e.value.(${goType})\n`);
      }
      this.push("}\n\n");
    }

    // Visitor interface.
    // Note: Go does not allow type parameters on methods, so Accept is a
    // package-level generic function rather than a method on the enum.
    this.push(`type ${className}_visitor[T any] interface {\n`);
    this.push("OnUnknown() T\n");
    for (const variant of constantVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      this.push(`On${name}Const() T\n`);
    }
    for (const variant of wrapperVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      const goType = typeSpeller.getGoType(variant.type!);
      const isStructType = this.isStructType(variant.type!);
      const paramType = isStructType ? `*${goType}` : goType;
      this.push(`On${name}Wrapper(v ${paramType}) T\n`);
    }
    this.push("}\n\n");

    // Accept function.
    this.push(
      `func ${className}_accept[T any](e ${className}, v ${className}_visitor[T]) T {\n`,
    );
    this.push("switch e.kind {\n");
    for (const variant of constantVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      this.push(`case ${kindType}_${name}Const:\n`);
      this.push(`return v.On${name}Const()\n`);
    }
    for (const variant of wrapperVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      this.push(`case ${kindType}_${name}Wrapper:\n`);
      this.push(`return v.On${name}Wrapper(e.Unwrap${name}())\n`);
    }
    this.push("default:\n");
    this.push("return v.OnUnknown()\n");
    this.push("}\n");
    this.push("}\n\n");

    // String() method.
    this.push(`func (e ${className}) String() string {\n`);
    this.push(
      `return ${className}_serializer().ToJson(e, skir_client.Readable{})\n`,
    );
    this.push("}\n\n");

    // Adapter.
    const qualifiedRecordName = record.recordAncestors
      .map((r) => r.name.text)
      .join(".");
    const kindCount = 1 + constantVariants.length + wrapperVariants.length;
    this.push(`var _${className}_adapter = skir_client.NewEnumAdapter(\n`);
    this.push(`${toGoStringLiteral(record.modulePath)},\n`);
    this.push(`${toGoStringLiteral(qualifiedRecordName)},\n`);
    this.push(`${toGoStringLiteral(docToCommentText(record.record.doc))},\n`);
    this.push(`func(e ${className}) int { return int(e.kind) },\n`);
    this.push(`${kindCount},\n`);
    this.push(`${className}{},\n`);
    this.push(
      `func(u *skir_client.Internal__UnrecognizedVariant) ${className} ` +
        `{ return ${className}{value: u} },\n`,
    );
    this.push(
      `func(e ${className}) *skir_client.Internal__UnrecognizedVariant {\n` +
        `if e.kind != ${kindType}_Unknown {\n` +
        `return nil\n` +
        `}\n` +
        `u, _ := e.value.(*skir_client.Internal__UnrecognizedVariant)\n` +
        `return u\n` +
        `},\n`,
    );
    this.push(")\n\n");

    // Serializer function.
    this.push(
      `func ${className}_serializer() skir_client.Serializer[${className}] {\n`,
    );
    this.push(`return _${className}_adapter.Serializer()\n`);
    this.push("}\n\n");

    // init() – register variants and finalize.
    this.push("func init() {\n");
    for (const variant of constantVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      this.push(
        `_${className}_adapter.AddConstantVariant(\n` +
          `${variant.number},\n` +
          `${toGoStringLiteral(variant.name.text)},\n` +
          `int(${kindType}_${name}Const),\n` +
          `${className}_${name}Const(),\n` +
          ")\n",
      );
    }
    for (const variant of wrapperVariants) {
      const name = convertCase(variant.name.text, "UpperCamel");
      const goType = typeSpeller.getGoType(variant.type!);
      const isStructType = this.isStructType(variant.type!);
      const serializerExpr = typeSpeller.getSerializerExpression(variant.type!);
      const getValueExpr = isStructType
        ? `func(e ${className}) ${goType} { return *e.Unwrap${name}() }`
        : `func(e ${className}) ${goType} { return e.Unwrap${name}() }`;
      this.push(
        `skir_client.AddWrapperVariant(\n` +
          `_${className}_adapter,\n` +
          `${variant.number},\n` +
          `${toGoStringLiteral(variant.name.text)},\n` +
          `int(${kindType}_${name}Wrapper),\n` +
          `${serializerExpr},\n` +
          `func(v ${goType}) ${className} { return ${className}_${name}Wrapper(v) },\n` +
          `${getValueExpr},\n` +
          ")\n",
      );
    }
    for (const removedNumber of record.record.removedNumbers) {
      this.push(`_${className}_adapter.AddRemovedNumber(${removedNumber})\n`);
    }
    this.push(`_${className}_adapter.Finalize()\n`);
    this.push("}\n\n");
  }

  private writeMethod(method: Method): void {
    const { typeSpeller } = this;
    const name = method.name.text;
    const requestGoType = typeSpeller.getGoType(method.requestType!);
    const responseGoType = typeSpeller.getGoType(method.responseType!);
    const requestSerializerExpr = typeSpeller.getSerializerExpression(
      method.requestType!,
    );
    const responseSerializerExpr = typeSpeller.getSerializerExpression(
      method.responseType!,
    );
    this.push(commentify(docToCommentText(method.doc)));
    this.push(
      `var ${convertCase(name, "UpperCamel")}_method = skir_client.Method[${requestGoType}, ${responseGoType}]{\n`,
    );
    this.push(`Name: ${toGoStringLiteral(name)},\n`);
    this.push(`Number: ${method.number},\n`);
    this.push(`RequestSerializer: ${requestSerializerExpr},\n`);
    this.push(`ResponseSerializer: ${responseSerializerExpr},\n`);
    this.push(`Doc: ${toGoStringLiteral(docToCommentText(method.doc))},\n`);
    this.push("}\n\n");
  }

  private writeConstant(constant: Constant): void {
    const { typeSpeller } = this;
    const goName = convertCase(constant.name.text, "UpperCamel").concat(
      "_const",
    );
    const type = constant.type!;
    const goType = typeSpeller.getGoType(type);
    const serializerExpr = typeSpeller.getSerializerExpression(type);
    const goStringLiteral = toGoStringLiteral(
      JSON.stringify(constant.valueAsDenseJson),
    );
    this.push(commentify(docToCommentText(constant.doc)));
    this.push(`var _${goName} *${goType} = nil\n\n`);
    this.push("func init() {\n");
    this.push(`  v, _ := ${serializerExpr}.FromJson(${goStringLiteral})\n`);
    this.push(`  _${goName} = &v\n`);
    this.push("}\n\n");
    this.push(`func ${goName}() *${goType} {\n`);
    this.push(`  return _${goName}\n`);
    this.push("}\n\n");
  }

  private getKeyedArrayHelper(type: ResolvedType): KeyedArrayHelper | null {
    if (type.kind !== "array") {
      return null;
    }
    const { key } = type;
    if (!key) {
      return null;
    }
    const { typeSpeller } = this;
    const itemType = typeSpeller.getGoType(type.item);
    const makeMapType = (comp: string): string => `map[${comp}]*${itemType}`;
    const keyAccessor = "e.".concat(
      key.path
        .map((p) => structFieldToGetterName(p.name.text).concat("()"))
        .join("."),
    );
    const { keyType } = key;
    switch (keyType.kind) {
      case "primitive": {
        switch (keyType.primitive) {
          case "bool":
          case "int32":
          case "int64":
          case "float32":
          case "float64":
          case "string":
          case "hash64": {
            // The simple case: the key type is already comparable.
            const comparableType = typeSpeller.getGoType(keyType);
            return {
              itemType: itemType,
              mapType: makeMapType(comparableType),
              exposedKeyType: comparableType,
              itemToComparableExpr: keyAccessor,
              exposedKeyToComparableExpr: "k",
            };
          }
          case "timestamp":
            return {
              itemType: itemType,
              mapType: makeMapType("int64"),
              exposedKeyType: "time.Time",
              itemToComparableExpr: keyAccessor.concat(".UnixMilli()"),
              exposedKeyToComparableExpr: "k.UnixMilli()",
            };
          case "bytes":
            return {
              itemType: itemType,
              mapType: makeMapType("string"),
              exposedKeyType: "skir_client.Bytes",
              itemToComparableExpr: keyAccessor.concat(".Hex()"),
              exposedKeyToComparableExpr: "k.Hex()",
            };
        }
        break;
      }
      case "record": {
        const comparableType = typeSpeller.getGoType(keyType).concat("_kind");
        return {
          itemType: itemType,
          mapType: makeMapType(comparableType),
          exposedKeyType: comparableType,
          itemToComparableExpr: keyAccessor,
          exposedKeyToComparableExpr: "k",
        };
      }
    }
  }

  private isStructType(type: ResolvedType): boolean {
    return (
      type.kind === "record" &&
      this.typeSpeller.recordMap.get(type.key)?.record.recordType === "struct"
    );
  }

  private pushSeparator(header: string): void {
    this.push(`// ${"=".repeat(78)}\n`);
    this.push(`// ${header}\n`);
    this.push(`// ${"=".repeat(78)}\n\n`);
  }

  private push(...code: string[]): void {
    this.code += code.join("");
  }

  private joinLinesAndFixFormatting(): string {
    const indentUnit = "\t";
    let result = "";
    // The indent at every line is obtained by repeating indentUnit N times,
    // where N is the length of this array.
    const contextStack: Array<"{" | "(" | "[" | "<" | ":" | "."> = [];
    // Returns the last element in `contextStack`.
    const peakTop = (): string => contextStack.at(-1)!;
    const getMatchingLeftBracket = (r: "}" | ")" | "]" | ">"): string => {
      switch (r) {
        case "}":
          return "{";
        case ")":
          return "(";
        case "]":
          return "[";
        case ">":
          return "<";
      }
    };
    for (let line of this.code.split("\n")) {
      line = line.trim();
      if (line.length <= 0) {
        // Don't indent empty lines.
        result += "\n";
        continue;
      }

      const firstChar = line[0];
      switch (firstChar) {
        case "}":
        case ")":
        case "]":
        case ">": {
          const left = getMatchingLeftBracket(firstChar);
          while (contextStack.pop() !== left) {
            if (contextStack.length <= 0) {
              throw Error();
            }
          }
          break;
        }
        case ".": {
          if (peakTop() !== ".") {
            contextStack.push(".");
          }
          break;
        }
      }
      const indent =
        indentUnit.repeat(contextStack.length) +
        (line.startsWith("*") ? " " : "");
      result += `${indent}${line.trimEnd()}\n`;
      if (line.startsWith("/") || line.startsWith("*")) {
        // A comment.
        continue;
      }
      const lastChar = line.slice(-1);
      switch (lastChar) {
        case "{":
        case "(":
        case "[":
        case "<": {
          // The next line will be indented
          contextStack.push(lastChar);
          break;
        }
        case ":":
        case "=": {
          if (peakTop() !== ":") {
            contextStack.push(":");
          }
          break;
        }
        case ";":
        case ",": {
          if (peakTop() === "." || peakTop() === ":") {
            contextStack.pop();
          }
        }
      }
    }

    return (
      result
        // Remove spaces enclosed within curly brackets if that's all there is.
        .replace(/\{\s+\}/g, "{}")
        // Remove spaces enclosed within round brackets if that's all there is.
        .replace(/\(\s+\)/g, "()")
        // Remove spaces enclosed within square brackets if that's all there is.
        .replace(/\[\s+\]/g, "[]")
        // Remove empty line following an open curly bracket.
        .replace(/(\{\n *)\n/g, "$1")
        // Remove empty line preceding a closed curly bracket.
        .replace(/\n(\n *\})/g, "$1")
        // Coalesce consecutive empty lines.
        .replace(/\n\n\n+/g, "\n\n")
        .replace(/\n\n$/g, "\n")
    );
  }

  private readonly typeSpeller: TypeSpeller;
  private code = "";
}

interface KeyedArrayHelper {
  /** Item (Go) type. */
  readonly itemType: string;
  /** Go type of the internal map. */
  readonly mapType: string;
  /** Key (Go) type exposed to the user. */
  readonly exposedKeyType: string;
  /** Go expression for extracting a comparable key from an item (e). */
  readonly itemToComparableExpr: string;
  /** Go expression for extracting a comparable key from an exposed key (k). */
  readonly exposedKeyToComparableExpr: string;
}

function toGoStringLiteral(input: string): string {
  const escaped = input
    .replace(/\\/g, "\\\\") // Escape backslashes
    .replace(/"/g, '\\"') // Escape double quotes
    .replace(/\n/g, "\\n") // Escape newlines
    .replace(/\r/g, "\\r") // Escape carriage returns
    .replace(/\t/g, "\\t"); // Escape tabs
  return `"${escaped}"`;
}

function commentify(textOrLines: string | readonly string[]): string {
  const text = (
    typeof textOrLines === "string" ? textOrLines : textOrLines.join("\n")
  )
    .trim()
    .replace(/\n{3,}/g, "\n\n");
  if (text.length <= 0) {
    return "";
  }
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? `// ${line}\n` : `//\n`))
    .join("");
}

function docToCommentText(doc: Doc): string {
  return doc.pieces
    .map((p) => {
      switch (p.kind) {
        case "text":
          return p.text;
        case "reference":
          return "`" + p.referenceRange.text.slice(1, -1) + "`";
      }
    })
    .join("");
}

export const GENERATOR = new GoCodeGenerator();
